

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 217)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 40, 350, 200))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.widthField = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.widthField.setFont(font)
        self.widthField.setObjectName("widthField")
        self.widthField.setPlaceholderText("inches")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.widthField)
        self.gapLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.gapLabel.setText("Label Gap : ")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gapLabel.setFont(font)
        self.gapLabel.setObjectName("gapLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gapLabel)
        self.gapField = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gapField.setFont(font)
        self.gapField.setObjectName("gapField")
        self.gapField.setPlaceholderText("inches")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gapField)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.heightField = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.heightField.setFont(font)
        self.heightField.setObjectName("heightField")
        self.heightField.setPlaceholderText("inches")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.heightField)
        self.btnOk = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.btnOk)
        self.printersList = QtWidgets.QComboBox(self.formLayoutWidget)
        self.printersList.setObjectName("printersList")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.printersList)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Label Width : "))
        self.label_2.setText(_translate("MainWindow", "Label Height : "))
        self.btnOk.setText(_translate("MainWindow", "OK"))
        self.label_3.setText(_translate("MainWindow", "Printer : "))
