
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QGraphicsScene, QWidget
from graphics import Ui_Form
from PyQt5 import QtCore, QtGui, QtWidgets
from GroupsDal import GroupsDal
from inputDialog import Ui_MainWindow as inputDialog
class Ui_MainWindow(QWidget):

    def graph(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.scene = QGraphicsScene()
        self.scene.setSceneRect(0, 0, 1600, 600)
        self.scene.setBackgroundBrush(QColor("white"))
        self.ui.graphicsView.setScene(self.scene)

    def inputDialog(self):
        self.inputWindow = QtWidgets.QMainWindow()
        self.inputUi = inputDialog()
        self.inputUi.setupUi(self.inputWindow)




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 500))
        palette = QtGui.QPalette()
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 1091, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.mailList = QtWidgets.QListWidget(self.pageHome)
        self.mailList.setGeometry(QtCore.QRect(30, 70, 501, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mailList.sizePolicy().hasHeightForWidth())
        self.mailList.setSizePolicy(sizePolicy)
        self.mailList.setObjectName("mailList")
        self.mailLabel = QtWidgets.QLabel(self.pageHome)
        self.mailLabel.setGeometry(QtCore.QRect(70, 0, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mailLabel.setFont(font)
        self.mailLabel.setObjectName("mailLabel")
        self.btnAddMailMain = QtWidgets.QPushButton(self.pageHome)
        self.btnAddMailMain.setEnabled(True)
        self.btnAddMailMain.setGeometry(QtCore.QRect(90, 290, 121, 51))
        self.btnAddMailMain.setObjectName("btnAddMailMain")
        self.btnRemoveMailMain = QtWidgets.QPushButton(self.pageHome)
        self.btnRemoveMailMain.setGeometry(QtCore.QRect(280, 290, 121, 51))
        self.btnRemoveMailMain.setObjectName("btnRemoveMailMain")
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.pageHome)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(620, 70, 361, 141))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.mailConfigAddress = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mailConfigAddress.setFont(font)
        self.mailConfigAddress.setObjectName("mailConfigAddress")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mailConfigAddress)
        self.mailConfigPassword = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mailConfigPassword.setFont(font)
        self.mailConfigPassword.setObjectName("mailConfigPassword")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mailConfigPassword)
        self.btnMailConfig = QtWidgets.QPushButton(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnMailConfig.setFont(font)
        self.btnMailConfig.setObjectName("btnMailConfig")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.btnMailConfig)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.providersMailConfig = QtWidgets.QComboBox(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.providersMailConfig.setFont(font)
        self.providersMailConfig.setObjectName("providersMailConfig")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.providersMailConfig)
        self.label_40 = QtWidgets.QLabel(self.pageHome)
        self.label_40.setGeometry(QtCore.QRect(830, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.senderList = QtWidgets.QListWidget(self.pageHome)
        self.senderList.setGeometry(QtCore.QRect(630, 220, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.senderList.setFont(font)
        self.senderList.setObjectName("senderList")
        self.btnRemoveSender = QtWidgets.QPushButton(self.pageHome)
        self.btnRemoveSender.setEnabled(True)
        self.btnRemoveSender.setGeometry(QtCore.QRect(600, 330, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRemoveSender.setFont(font)
        self.btnRemoveSender.setObjectName("btnRemoveSender")
        self.btnSelectSender = QtWidgets.QPushButton(self.pageHome)
        self.btnSelectSender.setEnabled(True)
        self.btnSelectSender.setGeometry(QtCore.QRect(800, 330, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelectSender.setFont(font)
        self.btnSelectSender.setObjectName("btnSelectSender")
        self.stackedWidget.addWidget(self.pageHome)
        self.pageInward = QtWidgets.QWidget()
        self.pageInward.setObjectName("pageInward")
        self.label_9 = QtWidgets.QLabel(self.pageInward)
        self.label_9.setGeometry(QtCore.QRect(450, 0, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget = QtWidgets.QWidget(self.pageInward)
        self.formLayoutWidget.setGeometry(QtCore.QRect(350, 60, 411, 62))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.barcodeNumbeFieldInward = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeNumbeFieldInward.setFont(font)
        self.barcodeNumbeFieldInward.setObjectName("barcodeNumbeFieldInward")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.barcodeNumbeFieldInward)
        self.btnSearchInward = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchInward.setFont(font)
        self.btnSearchInward.setObjectName("btnSearchInward")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.btnSearchInward)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.pageInward)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(70, 180, 300, 126))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.productNameFieldInward = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.productNameFieldInward.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.productNameFieldInward.setFont(font)
        self.productNameFieldInward.setObjectName("productNameFieldInward")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productNameFieldInward)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.currentQuantityFieldInward = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.currentQuantityFieldInward.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentQuantityFieldInward.setFont(font)
        self.currentQuantityFieldInward.setObjectName("currentQuantityFieldInward")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentQuantityFieldInward)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.inwardAmountFieldInward = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inwardAmountFieldInward.setFont(font)
        self.inwardAmountFieldInward.setObjectName("inwardAmountFieldInward")
        self.inwardAmountFieldInward.setMaximum(1000)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inwardAmountFieldInward)
        self.btnUpdateInward = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdateInward.sizePolicy().hasHeightForWidth())
        self.btnUpdateInward.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        self.btnUpdateInward.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateInward.setFont(font)
        self.btnUpdateInward.setObjectName("btnUpdateInward")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.btnUpdateInward)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.pageInward)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(400, 180, 300, 291))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.skuLayoutInward = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.skuLayoutInward.setContentsMargins(0, 0, 0, 0)
        self.skuLayoutInward.setObjectName("skuLayoutInward")
        groups = GroupsDal.getGroups()
        self.btnExportInward = QtWidgets.QPushButton(self.pageInward)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExportInward.sizePolicy().hasHeightForWidth())
        self.btnExportInward.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        self.btnExportInward.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExportInward.setFont(font)
        self.btnExportInward.setObjectName("btnExportInward")
        self.btnExportInward.setGeometry(QtCore.QRect(850, 50,150,40))
        self.btnExportInward.setText("Export Inward")
        self.inwardSkusLabel = []
        self.inwardSkusField = []
        i = 0
        for group in groups:

                self.inwardSkusLabel.append(QtWidgets.QLabel(self.formLayoutWidget_6))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.inwardSkusLabel[i].setFont(font)
                self.inwardSkusLabel[i].setObjectName("label_18")
                self.skuLayoutInward.setWidget(i, QtWidgets.QFormLayout.LabelRole, self.inwardSkusLabel[i])
                self.inwardSkusField.append(QtWidgets.QLineEdit(self.formLayoutWidget_6))
                self.inwardSkusField[i].setEnabled(False)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.inwardSkusField[i].setFont(font)
                self.inwardSkusField[i].setObjectName(group[1] + "Field")
                self.skuLayoutInward.setWidget(i, QtWidgets.QFormLayout.FieldRole, self.inwardSkusField[i])
                self.inwardSkusLabel[i].setText(group[1] + " :")
                i += 1

        self.imageLabelInward = QtWidgets.QLabel(self.pageInward)
        self.imageLabelInward.setGeometry(QtCore.QRect(760, 140, 291, 150))
        self.imageLabelInward.setText("")
        self.imageLabelInward.setStyleSheet("border: 3px solid gray;")
        self.imageLabelInward.setScaledContents(True)
        self.imageLabelInward.setObjectName("imageLabelInward")
        self.imageLabel2Inward = QtWidgets.QLabel(self.pageInward)
        self.imageLabel2Inward.setGeometry(QtCore.QRect(760, 300, 291, 150))
        self.imageLabel2Inward.setText("")
        self.imageLabel2Inward.setStyleSheet("border: 3px solid gray;")
        self.imageLabel2Inward.setScaledContents(True)
        self.imageLabel2Inward.setObjectName("imageLabel2Inward")
        self.stackedWidget.addWidget(self.pageInward)
        self.pageOutward = QtWidgets.QWidget()
        self.pageOutward.setObjectName("pageOutward")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.pageOutward)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(60, 190, 300, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.productNameFieldOutward = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.productNameFieldOutward.setFont(font)
        self.productNameFieldOutward.setObjectName("productNameFieldOutward")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productNameFieldOutward)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.quantityFieldOutward = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.quantityFieldOutward.setFont(font)
        self.quantityFieldOutward.setObjectName("quantityFieldOutward")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.quantityFieldOutward)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.inwardDateFieldOutward = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inwardDateFieldOutward.setFont(font)
        self.inwardDateFieldOutward.setObjectName("inwardDateFieldOutward")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inwardDateFieldOutward)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.outwardAmountFieldOutward = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outwardAmountFieldOutward.setFont(font)
        self.outwardAmountFieldOutward.setObjectName("outwardAmountFieldOutward")
        self.outwardAmountFieldOutward.setMaximum(1000)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.outwardAmountFieldOutward)
        self.btnOutwardPush = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOutwardPush.setFont(font)
        self.btnOutwardPush.setObjectName("btnOutwardPush")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.btnOutwardPush)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.pageOutward)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(330, 60, 431, 71))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.btnSearchOutward = QtWidgets.QPushButton(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchOutward.setFont(font)
        self.btnSearchOutward.setObjectName("btnSearchOutward")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.btnSearchOutward)
        self.barcodeNumberFieldOutward = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.barcodeNumberFieldOutward.setFont(font)
        self.barcodeNumberFieldOutward.setObjectName("barcodeNumberFieldOutward")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.barcodeNumberFieldOutward)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_16 = QtWidgets.QLabel(self.pageOutward)
        self.label_16.setGeometry(QtCore.QRect(100, 140, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.pageOutward)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(400, 190, 300, 311))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.skuLayoutOutward = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.skuLayoutOutward.setContentsMargins(0, 0, 0, 0)
        self.skuLayoutOutward.setObjectName("skuLayoutOutward")
        self.outwardLabels = []
        self.outwardFields = []
        i = 0
        for group in groups:
                self.outwardLabels.append(QtWidgets.QLabel(self.formLayoutWidget_5))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.outwardLabels[i].setFont(font)
                self.outwardLabels[i].setObjectName("label_17")
                self.skuLayoutOutward.setWidget(i, QtWidgets.QFormLayout.LabelRole, self.outwardLabels[i])
                self.outwardFields.append(QtWidgets.QLineEdit(self.formLayoutWidget_5))
                self.outwardFields[i].setEnabled(False)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.outwardFields[i].setFont(font)
                self.outwardFields[i].setObjectName(group[1] + "Outward")
                self.skuLayoutOutward.setWidget(i, QtWidgets.QFormLayout.FieldRole, self.outwardFields[i])
                self.outwardLabels[i].setText(group[1] + " : ")
                i += 1
        self.label_33 = QtWidgets.QLabel(self.pageOutward)
        self.label_33.setGeometry(QtCore.QRect(470, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.imageLabelOutward = QtWidgets.QLabel(self.pageOutward)
        self.imageLabelOutward.setGeometry(QtCore.QRect(760, 140, 291, 150))
        self.imageLabelOutward.setText("")
        self.imageLabelOutward.setScaledContents(True)
        self.imageLabelOutward.setObjectName("imageLabelOutward")
        self.imageLabelOutward.setStyleSheet("border: 3px solid gray;")
        self.imageLabel2Outward = QtWidgets.QLabel(self.pageOutward)
        self.imageLabel2Outward.setGeometry(QtCore.QRect(760, 300, 291, 150))
        self.imageLabel2Outward.setText("")
        self.imageLabel2Outward.setScaledContents(True)
        self.imageLabel2Outward.setObjectName("imageLabel2Outward")
        self.imageLabel2Outward.setStyleSheet("border: 3px solid gray;")
        self.btnExportOutward = QtWidgets.QPushButton(self.pageOutward)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExportOutward.sizePolicy().hasHeightForWidth())
        self.btnExportOutward.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        self.btnExportOutward.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExportOutward.setFont(font)
        self.btnExportOutward.setObjectName("btnExportOutward")
        self.btnExportOutward.setGeometry(QtCore.QRect(850, 50, 150, 40))
        self.btnExportOutward.setText("Export Outward")
        self.stackedWidget.addWidget(self.pageOutward)
        self.pageAnalysis = QtWidgets.QWidget()
        self.pageAnalysis.setObjectName("pageAnalaysis")
        self.label_3 = QtWidgets.QLabel(self.pageAnalysis)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.chart = QtWidgets.QLabel(self.pageAnalysis)
        self.chart.setGeometry(QtCore.QRect(90, 50, 891, 400))
        self.chart.setScaledContents(True)
        self.chart.setObjectName("chart")
        self.stackedWidget.addWidget(self.pageAnalysis)
        self.pageNewProduct = QtWidgets.QWidget()
        self.pageNewProduct.setObjectName("pageNewProduct")
        self.label_4 = QtWidgets.QLabel(self.pageNewProduct)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.pageNewProduct)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 200, 901, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.barcodeNumberFieldNew = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeNumberFieldNew.setFont(font)
        self.barcodeNumberFieldNew.setObjectName("barcodeNumberFieldNew")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.barcodeNumberFieldNew)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.productNameFieldNew = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.productNameFieldNew.setFont(font)
        self.productNameFieldNew.setObjectName("productNameFieldNew")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productNameFieldNew)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.quantityFieldNew = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.quantityFieldNew.setFont(font)
        self.quantityFieldNew.setObjectName("quantityFieldNew")
        self.quantityFieldNew.setMaximum(1000)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.quantityFieldNew)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.btnImage1 = QtWidgets.QToolButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnImage1.setFont(font)
        self.btnImage1.setObjectName("btnImage1")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnImage1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.btnImage2 = QtWidgets.QToolButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnImage2.setFont(font)
        self.btnImage2.setObjectName("btnImage2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnImage2)
        self.gridLayout.addLayout(self.formLayout_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.inputs = []
        self.labels = []
        i = 0
        for group in groups:
                self.labels.append(QtWidgets.QLabel(self.layoutWidget))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.labels[i].setFont(font)
                self.formLayout_5.setWidget(i, QtWidgets.QFormLayout.LabelRole, self.labels[i])
                self.inputs.append(QtWidgets.QLineEdit(self.layoutWidget))
                self.inputs[i].setEnabled(True)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.inputs[i].setFont(font)
                self.inputs[i].setObjectName(group[1])
                self.formLayout_5.setWidget(i, QtWidgets.QFormLayout.FieldRole, self.inputs[i])
                self.labels[i].setText(group[1] + " :")
                i += 1
        self.gridLayout.addLayout(self.formLayout_5, 0, 2, 1, 1)
        self.btnAddProduct = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddProduct.setFont(font)
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.gridLayout.addWidget(self.btnAddProduct, 0, 1, 1, 1)
        self.imageLabelNewProduct = QtWidgets.QLabel(self.pageNewProduct)
        self.imageLabelNewProduct.setGeometry(QtCore.QRect(150, 80, 351, 200))
        self.imageLabelNewProduct.setStyleSheet("border: 3px solid gray;")
        self.imageLabelNewProduct.setScaledContents(True)
        self.imageLabelNewProduct.setObjectName("imageLabelNewProduct")
        self.imageLabel2NewProduct = QtWidgets.QLabel(self.pageNewProduct)
        self.imageLabel2NewProduct.setGeometry(QtCore.QRect(570, 80, 391, 200))
        self.imageLabel2NewProduct.setStyleSheet("border: 3px solid gray;")
        self.imageLabel2NewProduct.setScaledContents(True)
        self.imageLabel2NewProduct.setObjectName("imageLabel2NewProduct")
        self.stackedWidget.addWidget(self.pageNewProduct)
        self.pageEditProduct = QtWidgets.QWidget()
        self.pageEditProduct.setObjectName("pageEditProduct")
        self.imageLabelEdit = QtWidgets.QLabel(self.pageEditProduct)
        self.imageLabelEdit.setGeometry(200, 0, 150, 100)
        self.imageLabelEdit.setStyleSheet("border: 3px solid gray;")
        self.imageLabelEdit.setScaledContents(True)
        self.imageLabelEdit.setObjectName("imageLabelEdit")
        self.imageLabel2Edit = QtWidgets.QLabel(self.pageEditProduct)
        self.imageLabel2Edit.setGeometry(750, 0, 150, 100)
        self.imageLabel2Edit.setStyleSheet("border: 3px solid gray;")
        self.imageLabel2Edit.setScaledContents(True)
        self.imageLabel2Edit.setObjectName("imageLabel2Edit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.pageEditProduct)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 50, 811, 336))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.barcodeNumberFieldEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeNumberFieldEdit.setFont(font)
        self.barcodeNumberFieldEdit.setObjectName("barcodeNumberFieldEdit")
        self.verticalLayout.addWidget(self.barcodeNumberFieldEdit)
        self.btnSearchEdit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchEdit.setFont(font)
        self.btnSearchEdit.setObjectName("btnSearchEdit")
        self.verticalLayout.addWidget(self.btnSearchEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.productNameFieldEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.productNameFieldEdit.setFont(font)
        self.productNameFieldEdit.setObjectName("productNameFieldEdit")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productNameFieldEdit)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.quantityFieldEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.quantityFieldEdit.setFont(font)
        self.quantityFieldEdit.setObjectName("quantityFieldEdit")
        self.quantityFieldEdit.setEnabled(False)
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.quantityFieldEdit)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.inwardDateFieldEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inwardDateFieldEdit.setFont(font)
        self.inwardDateFieldEdit.setObjectName("inwardDateFieldEdit")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inwardDateFieldEdit)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.soldFieldEdit = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.soldFieldEdit.setFont(font)
        self.soldFieldEdit.setObjectName("soldFieldEdit")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.soldFieldEdit)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.btnImage1Edit = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnImage1Edit.setFont(font)
        self.btnImage1Edit.setObjectName("btnImage1Edit")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnImage1Edit)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.btnImage2Edit = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnImage2Edit.setFont(font)
        self.btnImage2Edit.setObjectName("btnImage2Edit")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btnImage2Edit)
        self.horizontalLayout_2.addLayout(self.formLayout_8)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.skusEditLabel = []
        self.skusEditField = []
        i = 0
        for group in groups:
                self.skusEditLabel.append(QtWidgets.QLabel(self.verticalLayoutWidget_2))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.skusEditLabel[i].setFont(font)
                self.formLayout_6.setWidget(i, QtWidgets.QFormLayout.LabelRole, self.skusEditLabel[i])
                self.skusEditField.append(QtWidgets.QLineEdit(self.verticalLayoutWidget_2))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.skusEditField[i].setFont(font)
                self.skusEditField[i].setObjectName(group[1] + "Edit")
                self.formLayout_6.setWidget(i, QtWidgets.QFormLayout.FieldRole, self.skusEditField[i])
                self.skusEditLabel[i].setText(group[1] + " : ")
                i += 1
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.btnUpdateEdit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateEdit.setFont(font)
        self.btnUpdateEdit.setObjectName("btnUpdateEdit")
        self.verticalLayout_2.addWidget(self.btnUpdateEdit)
        self.label_29 = QtWidgets.QLabel(self.pageEditProduct)
        self.label_29.setGeometry(QtCore.QRect(420, 0, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.stackedWidget.addWidget(self.pageEditProduct)
        self.pageCatalogue = QtWidgets.QWidget()
        self.pageCatalogue.setObjectName("pageCatalogue")
        self.label_6 = QtWidgets.QLabel(self.pageCatalogue)
        self.label_6.setGeometry(QtCore.QRect(290, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.productListCatalogue = QtWidgets.QTableWidget(self.pageCatalogue)
        self.productListCatalogue.setGeometry(QtCore.QRect(240, 50, 611, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productListCatalogue.sizePolicy().hasHeightForWidth())
        self.productListCatalogue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.productListCatalogue.setFont(font)
        self.productListCatalogue.setLineWidth(3)
        self.productListCatalogue.setColumnCount(3)
        self.productListCatalogue.setObjectName("productListCatalogue")
        self.productListCatalogue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.productListCatalogue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.productListCatalogue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.productListCatalogue.setHorizontalHeaderItem(2, item)
        self.productListCatalogue.horizontalHeader().setDefaultSectionSize(200)
        self.btnNextCatalogue = QtWidgets.QPushButton(self.pageCatalogue)
        self.btnNextCatalogue.setGeometry(QtCore.QRect(880, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnNextCatalogue.setFont(font)
        self.btnNextCatalogue.setObjectName("btnNextCatalogue")
        self.btnExportCatalogue = QtWidgets.QPushButton(self.pageCatalogue)
        self.btnExportCatalogue.setGeometry(QtCore.QRect(880, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExportCatalogue.setFont(font)
        self.btnExportCatalogue.setObjectName("btnExportCatalogue")
        self.btnExportCatalogue.setText("Export")
        self.btnPreviousCatalogue = QtWidgets.QPushButton(self.pageCatalogue)
        self.btnPreviousCatalogue.setGeometry(QtCore.QRect(880, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPreviousCatalogue.setFont(font)
        self.btnPreviousCatalogue.setObjectName("btnPreviousCatalogue")
        self.imageLabel1Catalogue = QtWidgets.QLabel(self.pageCatalogue)
        self.imageLabel1Catalogue.setGeometry(QtCore.QRect(150, 320, 300, 150))
        self.imageLabel1Catalogue.setText("")
        self.imageLabel1Catalogue.setTextFormat(QtCore.Qt.AutoText)
        self.imageLabel1Catalogue.setStyleSheet("border:3px solid gray;")
        self.imageLabel1Catalogue.setScaledContents(True)
        self.imageLabel1Catalogue.setObjectName("imageLabel1Catalogue")
        self.imageLabel2Catalogue = QtWidgets.QLabel(self.pageCatalogue)
        self.imageLabel2Catalogue.setGeometry(QtCore.QRect(600, 320, 300, 150))
        self.imageLabel2Catalogue.setText("")
        self.imageLabel2Catalogue.setTextFormat(QtCore.Qt.AutoText)
        self.imageLabel2Catalogue.setStyleSheet("border:3px solid gray;")
        self.imageLabel2Catalogue.setScaledContents(True)
        self.imageLabel2Catalogue.setObjectName("imageLabel2Catalogue")
        self.stackedWidget.addWidget(self.pageCatalogue)
        self.pageGroup = QtWidgets.QWidget()
        self.pageGroup.setObjectName("pageGroup")
        self.groupsList = QtWidgets.QListWidget(self.pageGroup)
        self.groupsList.setGeometry(QtCore.QRect(200, 100, 601, 321))
        self.groupsList.setObjectName("groupsList")
        self.btnAddCompany = QtWidgets.QPushButton(self.pageGroup)
        self.btnAddCompany.setGeometry(QtCore.QRect(820, 210, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddCompany.setFont(font)
        self.btnAddCompany.setObjectName("btnAddCompany")
        self.btnRemoveCompany = QtWidgets.QPushButton(self.pageGroup)
        self.btnRemoveCompany.setGeometry(QtCore.QRect(820, 310, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRemoveCompany.setFont(font)
        self.btnRemoveCompany.setObjectName("btnRemoveCompany")
        self.label_7 = QtWidgets.QLabel(self.pageGroup)
        self.label_7.setGeometry(QtCore.QRect(350, 30, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.pageGroup)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.page)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(250, 90, 461, 71))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.barcodeLabelPrint = QtWidgets.QLabel(self.page)
        self.barcodeLabelPrint.setGeometry(QtCore.QRect(70, 180, 961, 300))
        self.barcodeLabelPrint.setText("")
        try:
                self.barcodeLabelPrint.setPixmap(QtGui.QPixmap("code.png"))
        except Exception:
                pass
        self.barcodeLabelPrint.setScaledContents(True)
        self.barcodeLabelPrint.setObjectName("barcodeLabelPrint")
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 1021, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnHome = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome.sizePolicy().hasHeightForWidth())
        self.btnHome.setSizePolicy(sizePolicy)
        self.btnHome.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnHome.setFont(font)
        self.btnHome.setObjectName("btnHome")
        self.horizontalLayout.addWidget(self.btnHome)
        self.btnInward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInward.sizePolicy().hasHeightForWidth())
        self.btnInward.setSizePolicy(sizePolicy)
        self.btnInward.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnInward.setFont(font)
        self.btnInward.setObjectName("btnInward")
        self.horizontalLayout.addWidget(self.btnInward)
        self.btnOutward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutward.sizePolicy().hasHeightForWidth())
        self.btnOutward.setSizePolicy(sizePolicy)
        self.btnOutward.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOutward.setFont(font)
        self.btnOutward.setObjectName("btnOutward")
        self.horizontalLayout.addWidget(self.btnOutward)
        self.btnAnalysis = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAnalysis.sizePolicy().hasHeightForWidth())
        self.btnAnalysis.setSizePolicy(sizePolicy)
        self.btnAnalysis.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAnalysis.setFont(font)
        self.btnAnalysis.setObjectName("btnAnalysis")
        self.horizontalLayout.addWidget(self.btnAnalysis)
        self.btnNewProduct = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewProduct.sizePolicy().hasHeightForWidth())
        self.btnNewProduct.setSizePolicy(sizePolicy)
        self.btnNewProduct.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewProduct.setFont(font)
        self.btnNewProduct.setObjectName("btnNewProduct")
        self.horizontalLayout.addWidget(self.btnNewProduct)
        self.btnEditProduct = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditProduct.sizePolicy().hasHeightForWidth())
        self.btnEditProduct.setSizePolicy(sizePolicy)
        self.btnEditProduct.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEditProduct.setFont(font)
        self.btnEditProduct.setObjectName("btnEditProduct")
        self.horizontalLayout.addWidget(self.btnEditProduct)
        self.btnCatalogue = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCatalogue.sizePolicy().hasHeightForWidth())
        self.btnCatalogue.setSizePolicy(sizePolicy)
        self.btnCatalogue.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCatalogue.setFont(font)
        self.btnCatalogue.setObjectName("btnCatalogue")
        self.horizontalLayout.addWidget(self.btnCatalogue)
        self.btnGroup = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGroup.sizePolicy().hasHeightForWidth())
        self.btnGroup.setSizePolicy(sizePolicy)
        self.btnGroup.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGroup.setFont(font)
        self.btnGroup.setObjectName("btnGroup")
        self.horizontalLayout.addWidget(self.btnGroup)
        self.btnPrint = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrint.sizePolicy().hasHeightForWidth())
        self.btnPrint.setSizePolicy(sizePolicy)
        self.btnPrint.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPrint.setFont(font)
        self.btnPrint.setObjectName("btnPrint")
        self.horizontalLayout.addWidget(self.btnPrint)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BarcodeApp"))
        self.mailLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mail List</p></body></html>"))
        self.btnAddMailMain.setText(_translate("MainWindow", "Add Mail"))
        self.btnRemoveMailMain.setText(_translate("MainWindow", "Remove Selected"))
        self.label_37.setText(_translate("MainWindow", "Mail Address : "))
        self.label_38.setText(_translate("MainWindow", "Password : "))
        self.btnMailConfig.setText(_translate("MainWindow", "Save"))
        self.label_39.setText(_translate("MainWindow", "Provider : "))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sender Mail </p></body></html>"))
        self.btnSelectSender.setText(_translate("MainWindow", "Select as Sender"))
        self.btnRemoveSender.setText(_translate("MainWindow", "Remove Selected"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Update Quantity</p><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Barcode Number : "))
        self.btnSearchInward.setText(_translate("MainWindow", "Search"))
        self.label_8.setText(_translate("MainWindow", "Product Name : "))
        self.label_13.setText(_translate("MainWindow", "Current Quantity :"))
        self.label_14.setText(_translate("MainWindow", "Inward Amount : "))
        self.btnUpdateInward.setText(_translate("MainWindow", "Update"))
        self.label_10.setText(_translate("MainWindow", "Product Name :"))
        self.label_11.setText(_translate("MainWindow", "Quantity :"))
        self.label_12.setText(_translate("MainWindow", "Inward Date :"))
        self.label_15.setText(_translate("MainWindow", "Outward Amount :"))
        self.btnOutwardPush.setText(_translate("MainWindow", "Out!"))
        self.btnSearchOutward.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Barcode Number :"))
        self.label_16.setText(_translate("MainWindow", "SKU Info"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Outward Product</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Top Selling Products</p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Add New Listing</p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "Barcode Number :"))
        self.label_20.setText(_translate("MainWindow", "Product Name :"))
        self.label_21.setText(_translate("MainWindow", "Quantity : "))
        self.label_22.setText(_translate("MainWindow", "Image 1 : "))
        self.btnImage1.setText(_translate("MainWindow", "..."))
        self.label_23.setText(_translate("MainWindow", "Image 2 : "))
        self.btnImage2.setText(_translate("MainWindow", "..."))
        self.btnAddProduct.setText(_translate("MainWindow", "Add Product"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Barcode Number</p></body></html>"))
        self.btnSearchEdit.setText(_translate("MainWindow", "Search"))
        self.label_25.setText(_translate("MainWindow", "Product Name :"))
        self.label_26.setText(_translate("MainWindow", "Quantity :"))
        self.label_27.setText(_translate("MainWindow", "Inward Date :"))
        self.label_28.setText(_translate("MainWindow", "Sold :"))
        self.label_30.setText(_translate("MainWindow", "Image 1 :"))
        self.btnImage1Edit.setText(_translate("MainWindow", "..."))
        self.label_31.setText(_translate("MainWindow", "Image 2 :"))
        self.btnImage2Edit.setText(_translate("MainWindow", "..."))
        self.btnUpdateEdit.setText(_translate("MainWindow", "Update"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Edit Item</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Product List </p></body></html>"))
        item = self.productListCatalogue.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Barcode Number"))
        item = self.productListCatalogue.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.productListCatalogue.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        self.btnNextCatalogue.setText(_translate("MainWindow", "Next"))
        self.btnPreviousCatalogue.setText(_translate("MainWindow", "Previous"))
        self.btnAddCompany.setText(_translate("MainWindow", "Add Company"))
        self.btnRemoveCompany.setText(_translate("MainWindow", "Remove Selected"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Group List</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "Barcode Number : "))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Barcode"))
        self.btnHome.setText(_translate("MainWindow", "Home"))
        self.btnInward.setText(_translate("MainWindow", "Inward"))
        self.btnOutward.setText(_translate("MainWindow", "Outward"))
        self.btnAnalysis.setText(_translate("MainWindow", "Analysis"))
        self.btnNewProduct.setText(_translate("MainWindow", "New Product"))
        self.btnEditProduct.setText(_translate("MainWindow", "Edit Product"))
        self.btnCatalogue.setText(_translate("MainWindow", "Catalogue"))
        self.btnGroup.setToolTip(_translate("MainWindow", "Groups"))
        self.btnGroup.setText(_translate("MainWindow", "Group"))
        self.btnPrint.setToolTip(_translate("MainWindow", "Groups"))
        self.btnPrint.setText(_translate("MainWindow", "Print"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
